### ISSUE TITLE
Improvement: Improve the UI / UX and code of the Attendance form

### ISSUE THREAD

**Issue by destroycompiler** [iiitl/college-management#38]
![Screenshot_20230420_133119](https://user-images.githubusercontent.com/11803841/233301544-490c0559-2535-450f-a653-335256a07b8a.png)

### The code is written completely in JSX and it has not been broken down into *React Components* making it harder to maintain the code later.
- The UI should look simple yet nice, and the code quality should be better.

**Comment by destroycompiler** [comment]
@deep-69bits I would like to improve the code quality, and redesign this piece of UI into a better form.

**Comment by deep-69bits** [comment]
@destroycompiler  alright

**Comment by destroycompiler** [comment]
Issue closed
